Submitting solution and tests for branch nc-news-6 (Ticket 7)
AnnaTas77/nc-news-backend-project pull request #6
Opened 2023-06-28 11:15 UTC by AnnaTas77

2023-06-28 11:33 UTC, EddTheDuck requested changes
Please add the tests mention in my comment and resubmit, thanks

2023-06-28 11:33 UTC, EddTheDuck commented on __tests__/app.test.js
> +
Please remove console.logs / commented out code

2023-06-28 11:33 UTC, EddTheDuck commented on __tests__/app.test.js
> +});
These are good tests but you shoudl also test for the following - 
Status 201, ignores unnecessary properties
Status 404, non existent ID, e.g. 0 or 9999
Status 404, username does not exist

2023-06-29 08:17 UTC, Dutton1990 approved these changes
Super refactor Anna, thanks for adding those new tests. Looks great to me you can merge and continue!

2023-06-29 08:45 UTC, merged